openapi: 3.0.3
info:
  title: Device Roaming Status
  description: |
    This API provides the API consumer with the ability to query device roaming Status

    # Introduction

    ## Roaming Status
    API consumer is able to verify whether a certain user device is in roaming situation (or not).

    The verification of the roaming situation depends on the network's ability. Additionally to the roaming status, when the device is in roaming situation, visited country information could be returned in the response.

    ## Possible Use-Cases
    Roaming status verification could be useful in scenario such as (not exhaustive):
      - For regulatory reasons, where a customer may need to be within a certain jurisdiction, or out with others, in order for transactions to be authorized
      - For security / fraud reasons, to establish that a customer is located where they claim to be
      - For service delivery reasons, to ensure that the customer has access to particular service, and will not incur roaming charges in accessing them

    ## Relevant terms and definitions

    * **Device**: A device refers to any physical entity that can connect to a network and participate in network communication.

        At least one identifier for the device (user equipment) out of four options must be provided: IPv4 address, IPv6 address, Phone number, or Network Access Identifier assigned by the mobile network operator for the device. Where more than one device identifier is provided, only one identifier will be selected by the implementation and this choice indicated to the API consumer in the session creation response.

        Note: Network Access Identifier is defined for future use and will not be supported with this version of the API.

    * **Roaming** : Roaming status - `true`, if device is in roaming situation - `false` else.

    * **Country** : Country code and name - visited country information, provided if the device is in roaming situation.

    * **LastStatusTime** : The time when the status was last confirmed to be correct. An older status is more likely to now be incorrect.

    # API Functionality

    The API exposes following capabilities:

    ## Device roaming situation

    The endpoint `POST /retrieve` allows to get roaming status and country information (if device in roaming situation) synchronously.

    <!-- CAMARA:MANDATORY:authorization-and-authentication:BEGIN -->

    # Authorization and authentication

    The "Camara Security and Interoperability Profile" provides details of how an API consumer requests an access token. Please refer to Identity and Consent Management (https://github.com/camaraproject/IdentityAndConsentManagement/) for the released version of the profile.

    The specific authorization flows to be used will be agreed upon during the onboarding process, happening between the API consumer and the API provider, taking into account the declared purpose for accessing the API, whilst also being subject to the prevailing legal framework dictated by local legislation.

    In cases where personal data is processed by the API and users can exercise their rights through mechanisms such as opt-in and/or opt-out, the use of three-legged access tokens is mandatory. This ensures that the API remains in compliance with privacy regulations, upholding the principles of transparency and user-centric privacy-by-design.
    <!-- CAMARA:MANDATORY:authorization-and-authentication:END -->

    <!-- CAMARA:MANDATORY:identifying-device-from-access-token:BEGIN -->

    # Identifying the device from the access token

    This API requires the API consumer to identify a device as the subject of the API as follows:
    - When the API is invoked using a two-legged access token, the subject will be identified from the optional `device` object, which therefore MUST be provided.
    - When a three-legged access token is used however, this optional identifier MUST NOT be provided, as the subject will be uniquely identified from the access token.

    This approach simplifies API usage for API consumers using a three-legged access token to invoke the API by relying on the information that is associated with the access token and was identified during the authentication process.

    ## Error handling:

    - If the subject cannot be identified from the access token and the optional `device` object is not included in the request, then the server will return an error with the `422 MISSING_IDENTIFIER` error code.

    - If the subject can be identified from the access token and the optional `device` object is also included in the request, then the server will return an error with the `422 UNNECESSARY_IDENTIFIER` error code. This will be the case even if the same device is identified by these two methods, as the server is unable to make this comparison.
    <!-- CAMARA:MANDATORY:identifying-device-from-access-token:END -->

    # Multi-SIM scenario handling

    In multi-SIM scenarios where more than one mobile device is associated with a phone number (e.g. a smartphone with an associated smartwatch), it might not be possible to uniquely identify the device for which the roaming status should be returned from that phone number. If the phone number is used as the device identifier when querying in a multi-SIM scenario, the API may:
    - respond with an error, or
    - return a combined roaming status for the multi-SIM group as a whole, or
    - return the roaming status for a single device in the multi-SIM group, which may not be the intended device.

    Possible solutions in such a scenario include:
    - Using the authorisation code flow to obtain an access token, which will automatically identify the intended device
    - Identifying the intended device from a unique identifier for that device, such as its source IP address and port
    - Check with the SIM provider whether a unique "secondary" phone number is already associated with each device, and use the secondary phone number to identify the intended device if available.

    <!-- CAMARA:MANDATORY:additional-error-responses:BEGIN -->

    # Additional CAMARA error responses

    The list of error codes in this API specification is not exhaustive. Therefore the API specification MAY not document some non-mandatory error statuses as indicated in `CAMARA API Design Guide`.

    Please refer to the `CAMARA_common.yaml` of the Commonalities Release associated to this API version for a complete list of error responses. The applicable Commonalities Release can be identified in the `API Readiness Checklist` document associated to this API version.

    As a specific rule, error `501 - NOT_IMPLEMENTED` can be only a possible error response if it is explicitly documented in the API.
    <!-- CAMARA:MANDATORY:additional-error-responses:END -->

    <!-- CAMARA:MANDATORY:request-body-strictness:BEGIN -->

    # Request body strictness

    This API rejects requests with JSON request bodies that contain properties not declared in this specification, at any nesting level. Unknown properties result in a `400 INVALID_ARGUMENT` response.
    <!-- CAMARA:MANDATORY:request-body-strictness:END -->

  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: wip
  x-camara-commonalities: wip

externalDocs:
  description: Product documentation at CAMARA
  url: https://github.com/camaraproject/DeviceRoamingStatus

servers:
  - url: "{apiRoot}/device-roaming-status/vwip"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root, defined by the service provider, e.g. `api.example.com` or `api.example.com/somepath`

tags:
  - name: Roaming Status Retrieval
    description: Operation to get device roaming status and country information (if roaming) synchronously

paths:
  /retrieve:
    post:
      tags:
        - Roaming Status Retrieval
      summary: "Get the current roaming status and the country information"
      description: Get the current roaming status and the country information
      operationId: getRoamingStatus
      parameters:
        - $ref: "../common/CAMARA_common.yaml#/components/parameters/x-correlator"
      security:
        - openId:
            - device-roaming-status:read
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoamingStatusRequest"
            examples:
              INPUT_PHONE_NUMBER:
                summary: Phone number
                description: Retrieve roaming status for a device identified by a phone number
                value:
                  device:
                    phoneNumber: "+123456789"
              INPUT_IP_ADDRESS_V4:
                summary: IPv4 address
                description: Retrieve roaming status for a device identified by an IPv4 address
                value:
                  device:
                    ipv4Address:
                      publicAddress: "123.234.1.2"
                      publicPort: 1234
              INPUT_IP_ADDRESS_V6:
                summary: IPv6 address
                description: Retrieve roaming status for a device identified by an IPv6 address
                value:
                  device:
                    ipv6Address: "2001:db8:85a3:8d3:1319:8a2e:370:7344"
              INPUT_NO_DEVICE:
                summary: Device not provided
                description: The device has to be deducted from token
                value:
                  {}
        required: true
      responses:
        "200":
          description: Contains information about current roaming status
          headers:
            x-correlator:
              $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoamingStatusResponse"
              examples:
                Not Roaming:
                  value:
                    lastStatusTime: "2024-02-20T10:41:38.657Z"
                    roaming: false
                No Country Name:
                  value:
                    lastStatusTime: "2024-02-20T10:41:38.657Z"
                    roaming: true
                    countryCode: 901
                    countryName: []
                Single Country Code:
                  value:
                    lastStatusTime: "2024-02-20T10:41:38.657Z"
                    roaming: true
                    countryCode: 262
                    countryName: ["DE"]
                Single Country Code With Device Disambiguation:
                  value:
                    device:
                      phoneNumber: "+123456789"
                    lastStatusTime: "2024-02-20T10:41:38.657Z"
                    roaming: true
                    countryCode: 262
                    countryName: ["DE"]
                Multiple Country Names:
                  value:
                    lastStatusTime: "2024-02-20T10:41:38.657Z"
                    roaming: true
                    countryCode: 340
                    countryName: ["BL", "GF", "GP", "MF", "MQ"]
        "400":
          $ref: "../common/CAMARA_common.yaml#/components/responses/Generic400"
        "401":
          $ref: "../common/CAMARA_common.yaml#/components/responses/Generic401"
        "403":
          $ref: "../common/CAMARA_common.yaml#/components/responses/Generic403"
        "404":
          $ref: "../common/CAMARA_common.yaml#/components/responses/Generic404"
        "422":
          $ref: "../common/CAMARA_common.yaml#/components/responses/Generic422"
        "429":
          $ref: "../common/CAMARA_common.yaml#/components/responses/Generic429"
        "503":
          $ref: "../common/CAMARA_common.yaml#/components/responses/Generic503"

components:
  securitySchemes:
    openId:
      $ref: "../common/CAMARA_common.yaml#/components/securitySchemes/openId"

  schemas:
    LastStatusTime:
      description: |
        The last time that the device roaming status was confirmed to be correct by the API provider. It might not be possible to provide the current status because, for example, the device may not be connected to any mobile network.
        It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.
      allOf:
        - $ref: "../common/CAMARA_common.yaml#/components/schemas/DateTime"

    ActiveRoaming:
      description: Roaming status. True, if it is roaming
      type: boolean

    CountryCode:
      description: The Mobile country code (MCC) as an geographic region identifier for the country and the dependent areas.
      type: integer
      format: int32
      minimum: 100
      maximum: 999

    CountryName:
      description: The ISO 3166 ALPHA-2 country-codes of mapped to mobile country code(MCC). If there is mapping of one MCC to multiple countries, then we have list of countries. If there is no mapping of MCC to any country, then an empty array [] shall be returned..
      type: array
      maxItems: 5
      items:
        description: The ISO 3166 ALPHA-2 country-code
        type: string
        maxLength: 2
        pattern: ^[A-Z]{2}$

    RoamingStatusResponse:
      description: The response body providing details of the roaming status of the requested device
      type: object
      required:
        - lastStatusTime
        - roaming
      properties:
        device:
          $ref: "../common/CAMARA_common.yaml#/components/schemas/DeviceResponse"
        lastStatusTime:
          $ref: "#/components/schemas/LastStatusTime"
        roaming:
          $ref: "#/components/schemas/ActiveRoaming"
        countryCode:
          $ref: "#/components/schemas/CountryCode"
        countryName:
          $ref: "#/components/schemas/CountryName"

    RoamingStatusRequest:
      description: The request body for retrieving the current roaming status for the requested device.
      type: object
      properties:
        device:
          $ref: "../common/CAMARA_common.yaml#/components/schemas/Device"
